apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: micro-apps
  app.kubernetes.io/managed-by: kustomize
commonAnnotations:
  org: acmeCorporation

resources:
  - service
  - elastic
  - nifi
  - postgres

configurations:
  - kconfig.yaml

secretGenerator:
  - name: secrets
    literals:
      - DATABASE_PASSWORD=fake
