apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: elastic
  app.kubernetes.io/instance: elastic-abcxzy
  app.kubernetes.io/component: infra
  app.kubernetes.io/part-of: micro-apps
  app.kubernetes.io/managed-by: kustomize
commonAnnotations:
  org: acmeCorporation

namePrefix: elastic-

resources:
  - statefulset.yml
  - service.yml

configMapGenerator:
  - name: env-vars
    literals:
      - ELASTIC_LOG_LEVEL=info
