certs:
  serverKey: certs/server-key.pem
  serverCert: certs/server-cert.pem
  clientKey: certs/client-key.pem
  clientCert: certs/client-cert.pem
  caCert: certs/ca-cert.pem
endpoints:
  account: http://localhost:8088
